// `npm run db:pull`: introspect the database with drizzle-kit and write libs/api/db/src/schema.ts.
//
// drizzle-kit pull (0.31) has two defects this script corrects:
// - tables referenced in `auth` are used but never declared, so `users` is imported from ./auth-schema;
// - composite foreign keys get their column lists paired in the wrong order, so they are rebuilt
//   from pg_constraint, which keeps the declared pairing;
// - an empty array default (`'{}'`) is read as `[""]`, so those columns get `.default([])`.
// Its relations.ts inherits the composite-key bug, so it is not kept.
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import postgres from 'postgres';

const config = 'libs/api/db/drizzle.config.ts';
const pulled = 'tmp/drizzle-pull/schema.ts';
const target = 'libs/api/db/src/schema.ts';

if (existsSync('.env.local')) process.loadEnvFile('.env.local');
const url = process.env.DATABASE_URL ?? 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';

const pull = spawnSync('npx', ['drizzle-kit', 'pull', '--config', config], { stdio: 'inherit', shell: true });
if (pull.status !== 0) process.exit(pull.status ?? 1);

const camel = (name) => name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

const sql = postgres(url, { max: 1, onnotice: () => undefined });
const compositeKeys = await sql`
  select
    c.conname as name,
    array(select a.attname::text from unnest(c.conkey) with ordinality k(attnum, i)
          join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum order by k.i) as columns,
    array(select a.attname::text from unnest(c.confkey) with ordinality k(attnum, i)
          join pg_attribute a on a.attrelid = c.confrelid and a.attnum = k.attnum order by k.i) as foreign_columns
  from pg_constraint c
  where c.contype = 'f' and c.connamespace = 'public'::regnamespace and cardinality(c.conkey) > 1`;
const emptyArrayDefaults = await sql`
  select column_name as name
  from information_schema.columns
  where table_schema = 'public' and data_type = 'ARRAY' and column_default ~ '^''\\{\\}''::'`;
await sql.end();

let source = readFileSync(pulled, 'utf8');

for (const fk of compositeKeys) {
  const block = new RegExp(
    `columns: \\[[^\\]]*\\],(\\s*)foreignColumns: \\[(\\w+)\\.[^\\]]*\\],(\\s*)name: "${fk.name}"`,
  );
  const match = source.match(block);
  if (!match) throw new Error(`Composite foreign key ${fk.name} not found in ${pulled}`);
  const [, gap1, foreignTable, gap2] = match;
  source = source.replace(
    block,
    `columns: [${fk.columns.map((c) => `table.${camel(c)}`).join(', ')}],${gap1}` +
      `foreignColumns: [${fk.foreign_columns.map((c) => `${foreignTable}.${camel(c)}`).join(', ')}],${gap2}` +
      `name: "${fk.name}"`,
  );
}

for (const column of emptyArrayDefaults) {
  const wrong = `("${column.name}").array().default([""])`;
  if (!source.includes(wrong)) throw new Error(`Array default of ${column.name} not found in ${pulled}`);
  source = source.replaceAll(wrong, `("${column.name}").array().default([])`);
}

if (/\busers\.id\b/.test(source)) {
  source = source.replace(/(import \{ sql \} from "drizzle-orm"\n)/, `$1import { users } from "./auth-schema"\n`);
}

const header =
  '// Generated by `npm run db:pull` from the local database. Do not edit by hand:\n' +
  '// change the SQL in supabase/migrations, run `npm run db:reset`, then `npm run db:pull`.\n' +
  '/* eslint-disable */\n';
writeFileSync(target, header + source);

const format = spawnSync('npx', ['prettier', '--write', target], { stdio: 'inherit', shell: true });
process.exit(format.status ?? 0);
