// Generated by `npm run db:pull` from the local database. Do not edit by hand:
// change the SQL in supabase/migrations, run `npm run db:reset`, then `npm run db:pull`.
/* eslint-disable */
import {
  pgTable,
  index,
  foreignKey,
  pgPolicy,
  uuid,
  text,
  jsonb,
  timestamp,
  check,
  unique,
  uniqueIndex,
  boolean,
  integer,
  type AnyPgColumn,
  bigint,
  real,
  primaryKey,
} from 'drizzle-orm/pg-core';
import type { PgTableExtraConfigValue } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './auth-schema';

export const auditEvents = pgTable(
  'audit_events',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    actorId: uuid('actor_id'),
    action: text().notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    diff: jsonb(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('audit_events_actor_id_idx').using('btree', table.actorId.asc().nullsLast().op('uuid_ops')),
    index('audit_events_space_id_created_at_idx').using(
      'btree',
      table.spaceId.asc().nullsLast().op('timestamptz_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'audit_events_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.actorId],
      foreignColumns: [users.id],
      name: 'audit_events_actor_id_fkey',
    }).onDelete('set null'),
    pgPolicy('audit events: admins and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`(( SELECT is_agency_staff() AS is_agency_staff) OR ( SELECT has_space_role(audit_events.space_id, '{admin}'::text[]) AS has_space_role))`,
    }),
  ],
);

export const organisations = pgTable(
  'organisations',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    name: text().notNull(),
    plan: text().default('agency').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    pgPolicy('organisations: agency staff and members read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`(( SELECT is_agency_staff() AS is_agency_staff) OR (EXISTS ( SELECT 1
   FROM spaces s
  WHERE ((s.organisation_id = organisations.id) AND (s.id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[]))))))`,
    }),
    check('organisations_name_check', sql`length(TRIM(BOTH FROM name)) > 0`),
  ],
);

export const spaces = pgTable(
  'spaces',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    organisationId: uuid('organisation_id').notNull(),
    name: text().notNull(),
    slug: text().notNull(),
    defaultLocale: text('default_locale').default('en-GB').notNull(),
    previewUrl: text('preview_url'),
    settings: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('spaces_organisation_id_idx').using('btree', table.organisationId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.organisationId],
      foreignColumns: [organisations.id],
      name: 'spaces_organisation_id_fkey',
    }).onDelete('restrict'),
    unique('spaces_slug_key').on(table.slug),
    pgPolicy('spaces: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('spaces: agency staff create', { as: 'permissive', for: 'insert', to: ['authenticated'] }),
    pgPolicy('spaces: admins and agency staff update', { as: 'permissive', for: 'update', to: ['authenticated'] }),
    check('spaces_name_check', sql`length(TRIM(BOTH FROM name)) > 0`),
    check('spaces_slug_check', sql`slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text`),
  ],
);

export const environments = pgTable(
  'environments',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    name: text().notNull(),
    isMain: boolean('is_main').default(false).notNull(),
    clonedFromId: uuid('cloned_from_id'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    uniqueIndex('environments_one_main_per_space_idx')
      .using('btree', table.spaceId.asc().nullsLast().op('uuid_ops'))
      .where(sql`is_main`),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'environments_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.clonedFromId, table.spaceId],
      foreignColumns: [table.id, table.spaceId],
      name: 'environments_cloned_from_id_space_id_fkey',
    }).onDelete('set null'),
    unique('environments_id_space_id_key').on(table.id, table.spaceId),
    unique('environments_space_id_name_key').on(table.spaceId, table.name),
    pgPolicy('environments: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('environments: admins and agency staff write', { as: 'permissive', for: 'all', to: ['authenticated'] }),
    check('environments_name_check', sql`name ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text`),
  ],
);

export const roles = pgTable(
  'roles',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    key: text().notNull(),
    name: text().notNull(),
    permissions: jsonb().default({}).notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'roles_space_id_fkey',
    }).onDelete('cascade'),
    unique('roles_id_space_id_key').on(table.id, table.spaceId),
    unique('roles_space_id_key_key').on(table.spaceId, table.key),
    pgPolicy('auth hook reads roles', {
      as: 'permissive',
      for: 'select',
      to: ['supabase_auth_admin'],
      using: sql`true`,
    }),
    pgPolicy('roles: members and agency staff read', { as: 'permissive', for: 'select', to: ['authenticated'] }),
    pgPolicy('roles: admins and agency staff write', { as: 'permissive', for: 'all', to: ['authenticated'] }),
    check('roles_key_check', sql`key ~ '^[a-z][a-z0-9_]*$'::text`),
  ],
);

export const profiles = pgTable(
  'profiles',
  {
    userId: uuid('user_id').primaryKey().notNull(),
    displayName: text('display_name'),
    avatarUrl: text('avatar_url'),
    isAgencyStaff: boolean('is_agency_staff').default(false).notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [users.id],
      name: 'profiles_user_id_fkey',
    }).onDelete('cascade'),
    pgPolicy('auth hook reads profiles', {
      as: 'permissive',
      for: 'select',
      to: ['supabase_auth_admin'],
      using: sql`true`,
    }),
    pgPolicy('profiles: self, co-members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
    }),
    pgPolicy('profiles: self update', { as: 'permissive', for: 'update', to: ['authenticated'] }),
  ],
);

export const contentTypes = pgTable(
  'content_types',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    apiId: text('api_id').notNull(),
    name: text().notNull(),
    kind: text().notNull(),
    description: text(),
    fields: jsonb().default([]).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('content_types_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'content_types_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'content_types_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    unique('content_types_id_space_id_key').on(table.id, table.spaceId),
    unique('content_types_id_environment_id_key').on(table.id, table.environmentId),
    unique('content_types_environment_id_api_id_key').on(table.environmentId, table.apiId),
    pgPolicy('content types: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('content types: admins, developers and agency staff write', {
      as: 'permissive',
      for: 'all',
      to: ['authenticated'],
    }),
    check('content_types_api_id_check', sql`(api_id ~ '^[a-z][a-zA-Z0-9]*$'::text) AND (length(api_id) <= 64)`),
    check('content_types_name_check', sql`length(TRIM(BOTH FROM name)) > 0`),
    check('content_types_kind_check', sql`kind = ANY (ARRAY['page'::text, 'entry'::text, 'singleton'::text])`),
    check('content_types_fields_check', sql`jsonb_typeof(fields) = 'array'::text`),
  ],
);

export const blockTypes = pgTable(
  'block_types',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    apiId: text('api_id').notNull(),
    name: text().notNull(),
    icon: text(),
    previewImagePath: text('preview_image_path'),
    fields: jsonb().default([]).notNull(),
    allowedChildren: text('allowed_children').array().default([]).notNull(),
    styleOptions: jsonb('style_options').default({}).notNull(),
    schemaVersion: integer('schema_version').default(1).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('block_types_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'block_types_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'block_types_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    unique('block_types_id_space_id_key').on(table.id, table.spaceId),
    unique('block_types_environment_id_api_id_key').on(table.environmentId, table.apiId),
    pgPolicy('block types: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('block types: admins, developers and agency staff write', {
      as: 'permissive',
      for: 'all',
      to: ['authenticated'],
    }),
    check('block_types_api_id_check', sql`(api_id ~ '^[a-z][a-zA-Z0-9]*$'::text) AND (length(api_id) <= 64)`),
    check('block_types_name_check', sql`length(TRIM(BOTH FROM name)) > 0`),
    check('block_types_icon_check', sql`icon ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text`),
    check('block_types_fields_check', sql`jsonb_typeof(fields) = 'array'::text`),
    check('block_types_style_options_check', sql`jsonb_typeof(style_options) = 'object'::text`),
    check('block_types_schema_version_check', sql`schema_version > 0`),
  ],
);

export const folders = pgTable(
  'folders',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    parentId: uuid('parent_id'),
    name: text().notNull(),
    slug: text().notNull(),
    path: text().default('').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('folders_parent_id_idx').using('btree', table.parentId.asc().nullsLast().op('uuid_ops')),
    index('folders_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'folders_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'folders_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.parentId, table.environmentId],
      foreignColumns: [table.id, table.environmentId],
      name: 'folders_parent_id_environment_id_fkey',
    }),
    unique('folders_id_space_id_key').on(table.id, table.spaceId),
    unique('folders_id_environment_id_key').on(table.id, table.environmentId),
    unique('folders_environment_id_path_key').on(table.environmentId, table.path),
    pgPolicy('folders: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('folders: authors and up create', { as: 'permissive', for: 'insert', to: ['authenticated'] }),
    pgPolicy('folders: editors and up update', { as: 'permissive', for: 'update', to: ['authenticated'] }),
    pgPolicy('folders: editors and up delete', { as: 'permissive', for: 'delete', to: ['authenticated'] }),
    check('folders_name_check', sql`(length(TRIM(BOTH FROM name)) > 0) AND (length(name) <= 120)`),
    check('folders_slug_check', sql`(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text) AND (length(slug) <= 100)`),
  ],
);

export const entries = pgTable(
  'entries',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    contentTypeId: uuid('content_type_id').notNull(),
    folderId: uuid('folder_id'),
    slug: text().notNull(),
    locale: text().notNull(),
    status: text().default('draft').notNull(),
    currentVersionId: uuid('current_version_id'),
    publishedVersionId: uuid('published_version_id'),
    publishedAt: timestamp('published_at', { withTimezone: true, mode: 'string' }),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table): PgTableExtraConfigValue[] => [
    uniqueIndex('entries_address_idx')
      .using(
        'btree',
        table.environmentId.asc().nullsLast().op('text_ops'),
        table.folderId.asc().nullsLast().op('uuid_ops'),
        table.slug.asc().nullsLast().op('uuid_ops'),
        table.locale.asc().nullsLast().op('text_ops'),
      )
      .where(sql`(deleted_at IS NULL)`),
    index('entries_content_type_id_idx').using('btree', table.contentTypeId.asc().nullsLast().op('uuid_ops')),
    index('entries_folder_id_idx').using('btree', table.folderId.asc().nullsLast().op('uuid_ops')),
    index('entries_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'entries_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [users.id],
      name: 'entries_created_by_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'entries_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.contentTypeId, table.environmentId],
      foreignColumns: [contentTypes.id, contentTypes.environmentId],
      name: 'entries_content_type_id_environment_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.folderId, table.environmentId],
      foreignColumns: [folders.id, folders.environmentId],
      name: 'entries_folder_id_environment_id_fkey',
    }),
    foreignKey({
      columns: [table.currentVersionId, table.id],
      foreignColumns: [entryVersions.id, entryVersions.entryId],
      name: 'entries_current_version_id_id_fkey',
    }),
    foreignKey({
      columns: [table.publishedVersionId, table.id],
      foreignColumns: [entryVersions.id, entryVersions.entryId],
      name: 'entries_published_version_id_id_fkey',
    }),
    unique('entries_id_space_id_key').on(table.id, table.spaceId),
    unique('entries_id_environment_id_key').on(table.id, table.environmentId),
    pgPolicy('entries: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('entries: authors and up create', { as: 'permissive', for: 'insert', to: ['authenticated'] }),
    pgPolicy('entries: authors and up update', { as: 'permissive', for: 'update', to: ['authenticated'] }),
    check('entries_slug_check', sql`(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text) AND (length(slug) <= 100)`),
    check('entries_locale_check', sql`locale ~ '^[a-z]{2,3}(-[A-Z]{2})?$'::text`),
    check(
      'entries_status_check',
      sql`status = ANY (ARRAY['draft'::text, 'in_review'::text, 'scheduled'::text, 'published'::text, 'archived'::text])`,
    ),
    check(
      'entries_check',
      sql`(status <> 'published'::text) OR ((published_version_id IS NOT NULL) AND (published_at IS NOT NULL))`,
    ),
  ],
);

export const entryVersions = pgTable(
  'entry_versions',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    entryId: uuid('entry_id').notNull(),
    spaceId: uuid('space_id').notNull(),
    data: jsonb().notNull(),
    message: text(),
    autosave: boolean().default(false).notNull(),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('entry_versions_created_by_idx').using('btree', table.createdBy.asc().nullsLast().op('uuid_ops')),
    index('entry_versions_entry_id_created_at_idx').using(
      'btree',
      table.entryId.asc().nullsLast().op('uuid_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    index('entry_versions_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'entry_versions_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [users.id],
      name: 'entry_versions_created_by_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.entryId, table.spaceId],
      foreignColumns: [entries.id, entries.spaceId],
      name: 'entry_versions_entry_id_space_id_fkey',
    }).onDelete('cascade'),
    unique('entry_versions_id_entry_id_key').on(table.id, table.entryId),
    pgPolicy('entry versions: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('entry versions: authors and up create their own', {
      as: 'permissive',
      for: 'insert',
      to: ['authenticated'],
    }),
    pgPolicy('entry versions: authors overwrite their own autosave', {
      as: 'permissive',
      for: 'update',
      to: ['authenticated'],
    }),
    check('entry_versions_data_check', sql`jsonb_typeof(data) = 'object'::text`),
    check('entry_versions_message_check', sql`length(message) <= 500`),
  ],
);

export const publishedContent = pgTable(
  'published_content',
  {
    entryId: uuid('entry_id').primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    contentTypeApiId: text('content_type_api_id').notNull(),
    fullPath: text('full_path').notNull(),
    locale: text().notNull(),
    data: jsonb().notNull(),
    publishedAt: timestamp('published_at', { withTimezone: true, mode: 'string' }).notNull(),
    cacheTags: text('cache_tags').array().default([]).notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    uniqueIndex('published_content_address_idx').using(
      'btree',
      table.environmentId.asc().nullsLast().op('text_ops'),
      table.locale.asc().nullsLast().op('text_ops'),
      table.fullPath.asc().nullsLast().op('uuid_ops'),
    ),
    index('published_content_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'published_content_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.entryId, table.spaceId],
      foreignColumns: [entries.id, entries.spaceId],
      name: 'published_content_entry_id_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.entryId, table.environmentId],
      foreignColumns: [entries.id, entries.environmentId],
      name: 'published_content_entry_id_environment_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'published_content_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    pgPolicy('published content: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('published content: editors and up write', { as: 'permissive', for: 'all', to: ['authenticated'] }),
    check('published_content_full_path_check', sql`full_path ~ '^(/[a-z0-9]+(-[a-z0-9]+)*)+$'::text`),
    check('published_content_data_check', sql`jsonb_typeof(data) = 'object'::text`),
  ],
);

export const assets = pgTable(
  'assets',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    path: text().notNull(),
    filename: text().notNull(),
    mime: text().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    sizeBytes: bigint('size_bytes', { mode: 'number' }).notNull(),
    width: integer(),
    height: integer(),
    focalX: real('focal_x'),
    focalY: real('focal_y'),
    alt: text(),
    title: text(),
    tags: text().array().default([]).notNull(),
    folder: text(),
    revision: integer().default(1).notNull(),
    uploadedBy: uuid('uploaded_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table): PgTableExtraConfigValue[] => [
    index('assets_space_id_created_at_idx').using(
      'btree',
      table.spaceId.asc().nullsLast().op('uuid_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    index('assets_tags_idx').using('gin', table.tags.asc().nullsLast().op('array_ops')),
    index('assets_uploaded_by_idx').using('btree', table.uploadedBy.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'assets_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.uploadedBy],
      foreignColumns: [users.id],
      name: 'assets_uploaded_by_fkey',
    }).onDelete('set null'),
    unique('assets_id_space_id_key').on(table.id, table.spaceId),
    pgPolicy('assets: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('assets: authors and up add their own', { as: 'permissive', for: 'insert', to: ['authenticated'] }),
    pgPolicy('assets: editors and up, or the author who uploaded it, update', {
      as: 'permissive',
      for: 'update',
      to: ['authenticated'],
    }),
    check('assets_filename_check', sql`filename ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,149}$'::text`),
    check('assets_mime_check', sql`mime ~ '^[a-z]+/[a-z0-9.+-]+$'::text`),
    check('assets_size_bytes_check', sql`(size_bytes > 0) AND (size_bytes <= 52428800)`),
    check('assets_width_check', sql`width > 0`),
    check('assets_height_check', sql`height > 0`),
    check('assets_focal_x_check', sql`(focal_x >= (0)::double precision) AND (focal_x <= (1)::double precision)`),
    check('assets_focal_y_check', sql`(focal_y >= (0)::double precision) AND (focal_y <= (1)::double precision)`),
    check('assets_alt_check', sql`length(alt) <= 500`),
    check('assets_title_check', sql`length(title) <= 200`),
    check('assets_tags_check', sql`(cardinality(tags) <= 30) AND (array_position(tags, NULL::text) IS NULL)`),
    check(
      'assets_folder_check',
      sql`((length(folder) >= 1) AND (length(folder) <= 200)) AND (folder !~ '(^/|/$|//)'::text)`,
    ),
    check('assets_revision_check', sql`revision > 0`),
    check(
      'assets_check',
      sql`path = ((((('spaces/'::text || space_id) || '/'::text) || id) || '/'::text) || filename)`,
    ),
    check('assets_check1', sql`(width IS NULL) = (height IS NULL)`),
    check('assets_check2', sql`(focal_x IS NULL) = (focal_y IS NULL)`),
  ],
);

export const apiTokens = pgTable(
  'api_tokens',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    environmentId: uuid('environment_id').notNull(),
    name: text().notNull(),
    scope: text().notNull(),
    tokenHash: text('token_hash').notNull(),
    tokenHint: text('token_hint').notNull(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true, mode: 'string' }),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true, mode: 'string' }),
  },
  (table): PgTableExtraConfigValue[] => [
    index('api_tokens_created_by_idx').using('btree', table.createdBy.asc().nullsLast().op('uuid_ops')),
    index('api_tokens_environment_id_idx').using('btree', table.environmentId.asc().nullsLast().op('uuid_ops')),
    index('api_tokens_space_id_idx').using(
      'btree',
      table.spaceId.asc().nullsLast().op('uuid_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'api_tokens_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [users.id],
      name: 'api_tokens_created_by_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.environmentId, table.spaceId],
      foreignColumns: [environments.id, environments.spaceId],
      name: 'api_tokens_environment_id_space_id_fkey',
    }).onDelete('cascade'),
    unique('api_tokens_token_hash_key').on(table.tokenHash),
    pgPolicy('api tokens: admins, developers and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`(( SELECT is_agency_staff() AS is_agency_staff) OR ( SELECT has_space_role(api_tokens.space_id, '{admin,developer}'::text[]) AS has_space_role))`,
    }),
    pgPolicy('api tokens: admins, developers and staff create as self', {
      as: 'permissive',
      for: 'insert',
      to: ['authenticated'],
    }),
    pgPolicy('api tokens: admins, developers and staff rename or revoke', {
      as: 'permissive',
      for: 'update',
      to: ['authenticated'],
    }),
    check('api_tokens_name_check', sql`(length(TRIM(BOTH FROM name)) > 0) AND (length(name) <= 120)`),
    check('api_tokens_scope_check', sql`scope = ANY (ARRAY['delivery'::text, 'preview'::text])`),
    check('api_tokens_token_hash_check', sql`token_hash ~ '^[0-9a-f]{64}$'::text`),
    check('api_tokens_token_hint_check', sql`token_hint ~ '^nv_(del|pre)_…[A-Za-z0-9_-]{4}$'::text`),
    check(
      'api_tokens_check',
      sql`"left"(token_hint, 7) =
CASE scope
    WHEN 'delivery'::text THEN 'nv_del_'::text
    ELSE 'nv_pre_'::text
END`,
    ),
  ],
);

export const assetUsages = pgTable(
  'asset_usages',
  {
    assetId: uuid('asset_id').notNull(),
    entryId: uuid('entry_id').notNull(),
    spaceId: uuid('space_id').notNull(),
    fieldPath: text('field_path').notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('asset_usages_entry_id_idx').using('btree', table.entryId.asc().nullsLast().op('uuid_ops')),
    index('asset_usages_space_id_idx').using('btree', table.spaceId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'asset_usages_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.assetId, table.spaceId],
      foreignColumns: [assets.id, assets.spaceId],
      name: 'asset_usages_asset_id_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.entryId, table.spaceId],
      foreignColumns: [entries.id, entries.spaceId],
      name: 'asset_usages_entry_id_space_id_fkey',
    }).onDelete('cascade'),
    primaryKey({ columns: [table.assetId, table.entryId, table.fieldPath], name: 'asset_usages_pkey' }),
    pgPolicy('asset usages: members and agency staff read', {
      as: 'permissive',
      for: 'select',
      to: ['authenticated'],
      using: sql`((space_id = ANY (( SELECT auth_space_ids() AS auth_space_ids)::uuid[])) OR ( SELECT is_agency_staff() AS is_agency_staff))`,
    }),
    pgPolicy('asset usages: editors and up add', { as: 'permissive', for: 'insert', to: ['authenticated'] }),
    pgPolicy('asset usages: editors and up remove', { as: 'permissive', for: 'delete', to: ['authenticated'] }),
    check('asset_usages_field_path_check', sql`(length(field_path) >= 1) AND (length(field_path) <= 500)`),
  ],
);

export const members = pgTable(
  'members',
  {
    spaceId: uuid('space_id').notNull(),
    userId: uuid('user_id').notNull(),
    roleId: uuid('role_id').notNull(),
    invitedBy: uuid('invited_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table): PgTableExtraConfigValue[] => [
    index('members_role_id_idx').using('btree', table.roleId.asc().nullsLast().op('uuid_ops')),
    index('members_user_id_idx').using('btree', table.userId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'members_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [users.id],
      name: 'members_user_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.invitedBy],
      foreignColumns: [users.id],
      name: 'members_invited_by_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.roleId, table.spaceId],
      foreignColumns: [roles.id, roles.spaceId],
      name: 'members_role_id_space_id_fkey',
    }).onDelete('restrict'),
    primaryKey({ columns: [table.spaceId, table.userId], name: 'members_pkey' }),
    pgPolicy('auth hook reads members', {
      as: 'permissive',
      for: 'select',
      to: ['supabase_auth_admin'],
      using: sql`true`,
    }),
    pgPolicy('members: members and agency staff read', { as: 'permissive', for: 'select', to: ['authenticated'] }),
    pgPolicy('members: admins and agency staff write', { as: 'permissive', for: 'all', to: ['authenticated'] }),
  ],
);
