// Generated by `npm run db:pull` from the local database. Do not edit by hand:
// change the SQL in supabase/migrations, run `npm run db:reset`, then `npm run db:pull`.
/* eslint-disable */
import {
  pgTable,
  index,
  foreignKey,
  uuid,
  text,
  jsonb,
  timestamp,
  check,
  unique,
  uniqueIndex,
  boolean,
  primaryKey,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './auth-schema';

export const auditEvents = pgTable(
  'audit_events',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    actorId: uuid('actor_id'),
    action: text().notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    diff: jsonb(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [
    index('audit_events_actor_id_idx').using('btree', table.actorId.asc().nullsLast().op('uuid_ops')),
    index('audit_events_space_id_created_at_idx').using(
      'btree',
      table.spaceId.asc().nullsLast().op('timestamptz_ops'),
      table.createdAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'audit_events_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.actorId],
      foreignColumns: [users.id],
      name: 'audit_events_actor_id_fkey',
    }).onDelete('set null'),
  ],
);

export const organisations = pgTable(
  'organisations',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    name: text().notNull(),
    plan: text().default('agency').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [check('organisations_name_check', sql`length(TRIM(BOTH FROM name)) > 0`)],
);

export const spaces = pgTable(
  'spaces',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    organisationId: uuid('organisation_id').notNull(),
    name: text().notNull(),
    slug: text().notNull(),
    defaultLocale: text('default_locale').default('en-GB').notNull(),
    previewUrl: text('preview_url'),
    settings: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [
    index('spaces_organisation_id_idx').using('btree', table.organisationId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.organisationId],
      foreignColumns: [organisations.id],
      name: 'spaces_organisation_id_fkey',
    }).onDelete('restrict'),
    unique('spaces_slug_key').on(table.slug),
    check('spaces_name_check', sql`length(TRIM(BOTH FROM name)) > 0`),
    check('spaces_slug_check', sql`slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text`),
  ],
);

export const environments = pgTable(
  'environments',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    name: text().notNull(),
    isMain: boolean('is_main').default(false).notNull(),
    clonedFromId: uuid('cloned_from_id'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex('environments_one_main_per_space_idx')
      .using('btree', table.spaceId.asc().nullsLast().op('uuid_ops'))
      .where(sql`is_main`),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'environments_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.clonedFromId, table.spaceId],
      foreignColumns: [table.id, table.spaceId],
      name: 'environments_cloned_from_id_space_id_fkey',
    }).onDelete('set null'),
    unique('environments_id_space_id_key').on(table.id, table.spaceId),
    unique('environments_space_id_name_key').on(table.spaceId, table.name),
    check('environments_name_check', sql`name ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text`),
  ],
);

export const roles = pgTable(
  'roles',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    spaceId: uuid('space_id').notNull(),
    key: text().notNull(),
    name: text().notNull(),
    permissions: jsonb().default({}).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'roles_space_id_fkey',
    }).onDelete('cascade'),
    unique('roles_id_space_id_key').on(table.id, table.spaceId),
    unique('roles_space_id_key_key').on(table.spaceId, table.key),
    check('roles_key_check', sql`key ~ '^[a-z][a-z0-9_]*$'::text`),
  ],
);

export const profiles = pgTable(
  'profiles',
  {
    userId: uuid('user_id').primaryKey().notNull(),
    displayName: text('display_name'),
    avatarUrl: text('avatar_url'),
    isAgencyStaff: boolean('is_agency_staff').default(false).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [users.id],
      name: 'profiles_user_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const members = pgTable(
  'members',
  {
    spaceId: uuid('space_id').notNull(),
    userId: uuid('user_id').notNull(),
    roleId: uuid('role_id').notNull(),
    invitedBy: uuid('invited_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [
    index('members_role_id_idx').using('btree', table.roleId.asc().nullsLast().op('uuid_ops')),
    index('members_user_id_idx').using('btree', table.userId.asc().nullsLast().op('uuid_ops')),
    foreignKey({
      columns: [table.spaceId],
      foreignColumns: [spaces.id],
      name: 'members_space_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [users.id],
      name: 'members_user_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.invitedBy],
      foreignColumns: [users.id],
      name: 'members_invited_by_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.roleId, table.spaceId],
      foreignColumns: [roles.id, roles.spaceId],
      name: 'members_role_id_space_id_fkey',
    }).onDelete('restrict'),
    primaryKey({ columns: [table.spaceId, table.userId], name: 'members_pkey' }),
  ],
);
